# Generated by Django 3.0.7 on 2020-07-05 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=255, null=True)),
                ('categories', models.TextField(null=True)),
                ('cover', models.BinaryField(editable=True, null=True)),
                ('pages', models.IntegerField(null=True)),
                ('progress', models.IntegerField(null=True)),
                ('file_name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('identifier', models.CharField(max_length=255, null=True)),
                ('publisher', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('rights', models.CharField(max_length=255, null=True)),
                ('tags', models.TextField(null=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('parent_id', models.IntegerField(null=True)),
                ('alt', models.CharField(max_length=255, null=True)),
                ('type', models.IntegerField(null=True)),
                ('socket', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'navigation',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('ulvl', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ManyToManyField(to='interface.Books')),
                ('uname', models.ManyToManyField(to='interface.Users')),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=255)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interface.Books')),
            ],
            options={
                'db_table': 'collections',
            },
        ),
    ]
