# Generated by Django 2.2.7 on 2020-01-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="books", options={"managed": False},),
    ]
