# Generated by Django 2.2.7 on 2020-01-01 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0002_auto_20200101_0445"),
    ]

    operations = [
        migrations.AlterModelOptions(name="books", options={},),
    ]
