# Generated by Django 3.0.2 on 2020-02-04 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0003_auto_20200101_0447"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collections",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection", models.CharField(max_length=255)),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="interface.Books",
                    ),
                ),
            ],
            options={"db_table": "collections",},
        ),
    ]
