# Generated by Django 3.0.4 on 2020-06-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0004_collections"),
    ]

    operations = [
        migrations.CreateModel(
            name="Navigation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255, null=True)),
                ("category", models.CharField(max_length=255, null=True)),
                ("parent_id", models.IntegerField(null=True)),
                ("alt", models.CharField(max_length=255, null=True)),
                ("type", models.IntegerField(null=True)),
                ("socket", models.CharField(max_length=255)),
            ],
            options={"db_table": "navigation",},
        ),
    ]
