# Generated by Django 3.0.7 on 2020-06-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_navigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('ulvl', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='identifier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(max_length=266, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='rights',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ManyToManyField(to='interface.Books')),
                ('uname', models.ManyToManyField(to='interface.Users')),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
    ]
