.TH "DataHooks.BookInterface" 3 "Sat Aug 9 2025 19:53:55" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataHooks.BookInterface
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconfig\fP = config"
.br
.ti -1c
.RI "\fBdb\fP = \fBStorage\fP(self\&.config)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Access point for book database\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "DataHooks\&.BookInterface\&.config = config"

.SS "DataHooks\&.BookInterface\&.db = \fBStorage\fP(self\&.config)"


.SH "Author"
.PP 
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
