.TH "DataHooks" 3 "Sat Mar 18 2023" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataHooks
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBookInterface\fP"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
pyShelf's frontend database hooks\&.
.fi
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
