.TH "FastAPIServer" 3 "Sat Mar 18 2023" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FastAPIServer
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFastAPIServer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBbase64decode\fP (string)"
.br
.ti -1c
.RI "str \fBsummarize\fP (string)"
.br
.ti -1c
.RI "str \fBconvertDateTime\fP (datetime timestamp)"
.br
.ti -1c
.RI "dumps \fBbooks_tojson\fP (obj)"
.br
.ti -1c
.RI "dumps \fBbook_tojson\fP (book)"
.br
.ti -1c
.RI "dumps \fBcollections_tojson\fP (collection)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "FastAPI \fBapp\fP = FastAPI()"
.br
.ti -1c
.RI "Jinja2Templates \fBtemplates\fP = Jinja2Templates(directory='src/frontend/templates')"
.br
.ti -1c
.RI "list \fBorigins\fP"
.br
.ti -1c
.RI "\fBallow_origins\fP"
.br
.ti -1c
.RI "\fBallow_credentials\fP"
.br
.ti -1c
.RI "\fBallow_methods\fP"
.br
.ti -1c
.RI "\fBallow_headers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
pyShelf's main frontend library\&.
.fi
.PP

.SH "Function Documentation"
.PP
.SS " str FastAPIServer\&.base64decode ( string)"

.PP
.nf
Decode a base64 string\&.
.fi
.PP

.SS " dumps FastAPIServer\&.book_tojson ( book)"

.PP
.nf
Convert a book object to a json\&.
.fi
.PP

.SS " dumps FastAPIServer\&.books_tojson ( obj)"

.PP
.nf
Convert an object to a dictionary\&.
.fi
.PP

.SS " dumps FastAPIServer\&.collections_tojson ( collection)"

.PP
.nf
Convert a collections object to json\&.
.fi
.PP

.SS " str FastAPIServer\&.convertDateTime (datetime timestamp)"

.PP
.nf
Convert a datetime object to a string\&.
.fi
.PP

.SS " str FastAPIServer\&.summarize ( string)"

.PP
.nf
Summarize a string\&.
.fi
.PP

.SH "Variable Documentation"
.PP
.SS "FastAPIServer\&.allow_credentials"

.SS "FastAPIServer\&.allow_headers"

.SS "FastAPIServer\&.allow_methods"

.SS "FastAPIServer\&.allow_origins"

.SS "FastAPI FastAPIServer\&.app = FastAPI()"

.SS "list FastAPIServer\&.origins"
\fBInitial value:\fP.PP
.nf
1 =  [
2     "http://localhost",
3     "http://localhost:8081",
4     "http://localhost:8080",
5     "*"
6 ]
.fi

.SS "Jinja2Templates FastAPIServer\&.templates = Jinja2Templates(directory='src/frontend/templates')"

.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
