.TH "objects.JSInterface" 3 "Sat Mar 18 2023" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
objects.JSInterface
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, Config config)"
.br
.ti -1c
.RI "def \fBinstall\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
A class to interface with the JavaScript side of pyShelf\&.
.fi
.PP

.SH "Constructor & Destructor Documentation"
.PP
.SS "def objects\&.JSInterface\&.__init__ ( self, Config config)"

.PP
.nf
Initialize the JSInterface object\&.
.fi
.PP

.SH "Member Function Documentation"
.PP
.SS "def objects\&.JSInterface\&.install ( self)"

.PP
.nf
Install the JavaScript dependencies\&.
.fi
.PP


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
