.TH "objects.JSInterface" 3 "Sat Aug 9 2025 19:53:55" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
objects.JSInterface
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, Config config)"
.br
.ti -1c
.RI "\fBinstall\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Path \fBpackage_json\fP = Path(config\&.root, 'src/frontend/package\&.json')"
.br
.ti -1c
.RI "Config \fBconfig\fP = config"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A class to interface with the JavaScript side of pyShelf\&.
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "objects\&.JSInterface\&.__init__ ( self, Config config)"

.PP
.nf
Initialize the JSInterface object\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "objects\&.JSInterface\&.install ( self)"

.PP
.nf
Install the JavaScript dependencies\&.
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "Config objects\&.JSInterface\&.config = config"

.SS "Path objects\&.JSInterface\&.package_json = Path(config\&.root, 'src/frontend/package\&.json')"


.SH "Author"
.PP 
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
