.TH "src.backend.lib.api_hooks.DuckDuckGo" 3 "Sat Aug 9 2025 19:53:55" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.lib.api_hooks.DuckDuckGo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBimage_result\fP (self, query)"
.br
.ti -1c
.RI "\fBdescription_result\fP (self, query)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "str \fBurl\fP = 'https://api\&.duckduckgo\&.com/?q='"
.br
.ti -1c
.RI "str \fBimageurl\fP = 'https://duckduckgo\&.com'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
duckduckgo related searching
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "src\&.backend\&.lib\&.api_hooks\&.DuckDuckGo\&.__init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "src\&.backend\&.lib\&.api_hooks\&.DuckDuckGo\&.description_result ( self,  query)"

.SS "src\&.backend\&.lib\&.api_hooks\&.DuckDuckGo\&.image_result ( self,  query)"

.PP
.nf
Returns json containing url to image
:param _key: &t=h_&iar=images&iax=images&ia=images&format=json&pretty=1

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "str src\&.backend\&.lib\&.api_hooks\&.DuckDuckGo\&.imageurl = 'https://duckduckgo\&.com'"

.SS "str src\&.backend\&.lib\&.api_hooks\&.DuckDuckGo\&.url = 'https://api\&.duckduckgo\&.com/?q='"


.SH "Author"
.PP 
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
