.TH "src.backend.lib.models.Book" 3 "Sat Mar 18 2023" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.lib.models.Book
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsrc\&.backend\&.lib\&.models\&.Base\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "Mapped \fBbook_id\fP = mapped_column(primary_key=True, nullable=False)"
.br
.ti -1c
.RI "Mapped \fBtitle\fP [str]"
.br
.ti -1c
.RI "Mapped \fBauthor\fP [Optional[str]]"
.br
.ti -1c
.RI "Mapped \fBcategories\fP [Optional[str]]"
.br
.ti -1c
.RI "Mapped \fBcover\fP [Optional[bytes]]"
.br
.ti -1c
.RI "Mapped \fBpages\fP [Optional[int]]"
.br
.ti -1c
.RI "Mapped \fBprogress\fP [Optional[float]]"
.br
.ti -1c
.RI "Mapped \fBfile_name\fP [str]"
.br
.ti -1c
.RI "Mapped \fBdescription\fP [Optional[str]]"
.br
.ti -1c
.RI "Mapped \fBdate\fP [timestamp]"
.br
.ti -1c
.RI "Mapped \fBrights\fP [Optional[str]]"
.br
.ti -1c
.RI "Mapped \fBtags\fP [Optional[str]]"
.br
.ti -1c
.RI "Mapped \fBidentifier\fP [Optional[str]]"
.br
.ti -1c
.RI "Mapped \fBpublisher\fP [Optional[str]]"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
Book model\&.
.fi
.PP

.SH "Member Data Documentation"
.PP
.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.author [Optional[str]]\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.book_id = mapped_column(primary_key=True, nullable=False)\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.categories [Optional[str]]\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.cover [Optional[bytes]]\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.date [timestamp]\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.description [Optional[str]]\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.file_name [str]\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.identifier [Optional[str]]\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.pages [Optional[int]]\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.progress [Optional[float]]\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.publisher [Optional[str]]\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.rights [Optional[str]]\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.tags [Optional[str]]\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Book\&.title [str]\fC [static]\fP"


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
