.TH "src.backend.lib.pyShelf.Admin" 3 "Sat Mar 18 2023" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.lib.pyShelf.Admin
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, root)"
.br
.ti -1c
.RI "def \fBcreatesuperuser\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconfig\fP"
.br
.ti -1c
.RI "\fBdb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
.SH "Constructor & Destructor Documentation"
.PP
.SS "def src\&.backend\&.lib\&.pyShelf\&.Admin\&.__init__ ( self,  root)"

.SH "Member Function Documentation"
.PP
.SS "def src\&.backend\&.lib\&.pyShelf\&.Admin\&.createsuperuser ( self)"

.SH "Member Data Documentation"
.PP
.SS "src\&.backend\&.lib\&.pyShelf\&.Admin\&.config"

.SS "src\&.backend\&.lib\&.pyShelf\&.Admin\&.db"


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
