.TH "src.backend.tests.library_test.TestCatalogue" 3 "Sat Mar 18 2023" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.tests.library_test.TestCatalogue
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_filter_books\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "os \fBroot\fP = os\&.path\&.abspath(os\&.path\&.curdir)"
.br
.ti -1c
.RI "\fBTest_Config\fP \fBconfig\fP = \fBTest_Config\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP
.SH "Member Function Documentation"
.PP
.SS "def src\&.backend\&.tests\&.library_test\&.TestCatalogue\&.test_filter_books ( self)"

.SH "Member Data Documentation"
.PP
.SS "\fBTest_Config\fP src\&.backend\&.tests\&.library_test\&.TestCatalogue\&.config = \fBTest_Config\fP()\fC [static]\fP"

.SS "os src\&.backend\&.tests\&.library_test\&.TestCatalogue\&.root = os\&.path\&.abspath(os\&.path\&.curdir)\fC [static]\fP"


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
