.TH "src.__main__" 3 "Sat Aug 9 2025 19:53:55" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.__main__
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBrun_import\fP ()"
.br
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBroot\fP = Path\&.cwd()"
.br
.ti -1c
.RI "\fBconfig\fP = \fBConfig\fP(root)"
.br
.ti -1c
.RI "\fBPRG_PATH\fP = Path\&.cwd()\&.__str__()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
PyShelf Entrypoint\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "src\&.__main__\&.main ()"

.PP
.nf
Program entrypoint\&.
.fi
.PP
 
.SS "src\&.__main__\&.run_import ()"

.PP
.nf
Begin live import of books\&.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "src\&.__main__\&.config = \fBConfig\fP(root)"

.SS "src\&.__main__\&.PRG_PATH = Path\&.cwd()\&.__str__()"

.SS "src\&.__main__\&.root = Path\&.cwd()"

.SH "Author"
.PP 
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
