.TH "src.backend.lib.overide.ACatalogue" 3 "Sat Mar 18 2023" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.lib.overide.ACatalogue
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsrc\&.backend\&.lib\&.library\&.Catalogue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBscan_folder\fP (self, _path=None)"
.br
.ti -1c
.RI "def \fBimport_books\fP (self, **kwargs)"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
Aynchronous overide of library\&.Catalogue,
: TODO : Complete or discard this overide

.fi
.PP

.SH "Constructor & Destructor Documentation"
.PP
.SS "def src\&.backend\&.lib\&.overide\&.ACatalogue\&.__init__ ( self)"

.PP
Reimplemented from \fBsrc\&.backend\&.lib\&.library\&.Catalogue\fP\&.
.SH "Member Function Documentation"
.PP
.SS "def src\&.backend\&.lib\&.overide\&.ACatalogue\&.import_books ( self, ** kwargs)"

.PP
.nf
Async overide of import_books

.fi
.PP

.PP
Reimplemented from \fBsrc\&.backend\&.lib\&.library\&.Catalogue\fP\&.
.SS "def src\&.backend\&.lib\&.overide\&.ACatalogue\&.scan_folder ( self,  _path = \fCNone\fP)"

.PP
.nf
Scan folder by _path, allows recurisive scanning

.fi
.PP

.PP
Reimplemented from \fBsrc\&.backend\&.lib\&.library\&.Catalogue\fP\&.

.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
