.TH "src.backend.lib.pyShelf.Server" 3 "Sat Aug 9 2025 19:53:55" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.lib.pyShelf.Server
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, root)"
.br
.ti -1c
.RI "\fB__aexit__\fP (self, *args, **kwargs)"
.br
.ti -1c
.RI "\fBinitialize_server\fP (self)"
.br
.ti -1c
.RI "\fBrunImport\fP (self)"
.br
.ti -1c
.RI "\fBsocketio\fP (self, websocket, path)"
.br
.ti -1c
.RI "\fBpong\fP (self)"
.br
.ti -1c
.RI "\fBstart\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBroot\fP = root"
.br
.ti -1c
.RI "tuple \fBhost\fP = ('127\&.0\&.0\&.1', 1337)"
.br
.ti -1c
.RI "\fBconfig\fP = \fBConfig\fP(self\&.root)"
.br
.ti -1c
.RI "\fBloop\fP = None"
.br
.ti -1c
.RI "\fBserve\fP = None"
.br
.ti -1c
.RI "\fBsocketio\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Main Server Container
:TODO: Document this

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.__init__ ( self,  root)"

.SH "Member Function Documentation"
.PP 
.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.__aexit__ ( self, * args, ** kwargs)"

.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.initialize_server ( self)"

.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.pong ( self)"

.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.runImport ( self)"

.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.socketio ( self,  websocket,  path)"

.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.start ( self)"

.SH "Member Data Documentation"
.PP 
.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.config = \fBConfig\fP(self\&.root)"

.SS "tuple src\&.backend\&.lib\&.pyShelf\&.Server\&.host = ('127\&.0\&.0\&.1', 1337)"

.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.loop = None"

.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.root = root"

.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.serve = None"

.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.socketio"


.SH "Author"
.PP 
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
