.TH "src.backend.tests.library_test.Test_Config" 3 "Sat Mar 18 2023" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.tests.library_test.Test_Config
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsrc\&.backend\&.lib\&.config\&.Config\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBopen_file\fP (self, root='config\&.json')"
.br
.in -1c
.SH "Detailed Description"
.PP
.SH "Constructor & Destructor Documentation"
.PP
.SS "def src\&.backend\&.tests\&.library_test\&.Test_Config\&.__init__ ( self)"

.PP
.nf
Initialize main configuration options\&.
.fi
.PP

.PP
Reimplemented from \fBsrc\&.backend\&.lib\&.config\&.Config\fP\&.
.SH "Member Function Documentation"
.PP
.SS "def src\&.backend\&.tests\&.library_test\&.Test_Config\&.open_file ( self,  root = \fC'config\&.json'\fP)"

.PP
.nf
Open config\&.json and reads in configuration options\&.
.fi
.PP

.PP
Reimplemented from \fBsrc\&.backend\&.lib\&.config\&.Config\fP\&.

.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
