.TH "src.backend.lib.models.Base" 3 "Sat Mar 18 2023" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.lib.models.Base
.SH SYNOPSIS
.br
.PP
.PP
Inherits DeclarativeBase\&.
.PP
Inherited by \fBsrc\&.backend\&.lib\&.models\&.Book\fP, and \fBsrc\&.backend\&.lib\&.models\&.Collection\fP\&.
.SH "Detailed Description"
.PP

.PP
.nf
Base class for all models\&.
.fi
.PP


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
