.TH "src.backend.tests.library_test.Test_Catalogue" 3 "Sat Mar 18 2023" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.tests.library_test.Test_Catalogue
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsrc\&.backend\&.lib\&.library\&.Catalogue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBfilter_books\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbook_shelf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
.SH "Constructor & Destructor Documentation"
.PP
.SS "def src\&.backend\&.tests\&.library_test\&.Test_Catalogue\&.__init__ ( self)"

.PP
Reimplemented from \fBsrc\&.backend\&.lib\&.library\&.Catalogue\fP\&.
.SH "Member Function Documentation"
.PP
.SS "def src\&.backend\&.tests\&.library_test\&.Test_Catalogue\&.filter_books ( self)"

.PP
.nf
Calls scan_folder and filters out book files\&.

:returns self\&._book_list_expanded: json string containing
all book metadata

.fi
.PP

.PP
Reimplemented from \fBsrc\&.backend\&.lib\&.library\&.Catalogue\fP\&.
.SH "Member Data Documentation"
.PP
.SS "src\&.backend\&.tests\&.library_test\&.Test_Catalogue\&.book_shelf"


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
