.TH "src.backend.lib.pyShelf.InitFiles" 3 "Sat Aug 9 2025 19:53:55" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.lib.pyShelf.InitFiles
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, file_array)"
.br
.ti -1c
.RI "\fBCreateFile\fP (self, _pointer)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
First run file creation operations
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "src\&.backend\&.lib\&.pyShelf\&.InitFiles\&.__init__ ( self,  file_array)"

.SH "Member Function Documentation"
.PP 
.SS "src\&.backend\&.lib\&.pyShelf\&.InitFiles\&.CreateFile ( self,  _pointer)"

.PP
.nf
Checks if file exists and creates it if not

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
