.TH "src.backend.lib.pyShelf.Server" 3 "Sat Mar 18 2023" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.lib.pyShelf.Server
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, root)"
.br
.ti -1c
.RI "def \fB__aexit__\fP (self, *args, **kwargs)"
.br
.ti -1c
.RI "def \fBinitialize_server\fP (self)"
.br
.ti -1c
.RI "def \fBrunImport\fP (self)"
.br
.ti -1c
.RI "def \fBsocketio\fP (self, websocket, path)"
.br
.ti -1c
.RI "def \fBpong\fP (self)"
.br
.ti -1c
.RI "def \fBstart\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBroot\fP"
.br
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBconfig\fP"
.br
.ti -1c
.RI "\fBloop\fP"
.br
.ti -1c
.RI "\fBserve\fP"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
Main Server Container
:TODO: Document this

.fi
.PP

.SH "Constructor & Destructor Documentation"
.PP
.SS "def src\&.backend\&.lib\&.pyShelf\&.Server\&.__init__ ( self,  root)"

.SH "Member Function Documentation"
.PP
.SS "def src\&.backend\&.lib\&.pyShelf\&.Server\&.__aexit__ ( self, * args, ** kwargs)"

.SS "def src\&.backend\&.lib\&.pyShelf\&.Server\&.initialize_server ( self)"

.SS "def src\&.backend\&.lib\&.pyShelf\&.Server\&.pong ( self)"

.SS "def src\&.backend\&.lib\&.pyShelf\&.Server\&.runImport ( self)"

.SS "def src\&.backend\&.lib\&.pyShelf\&.Server\&.socketio ( self,  websocket,  path)"

.SS "def src\&.backend\&.lib\&.pyShelf\&.Server\&.start ( self)"

.SH "Member Data Documentation"
.PP
.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.config"

.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.host"

.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.loop"

.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.root"

.SS "src\&.backend\&.lib\&.pyShelf\&.Server\&.serve"


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
