.TH "src.backend.lib.models.Collection" 3 "Sat Mar 18 2023" "Version 0.8.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.lib.models.Collection
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsrc\&.backend\&.lib\&.models\&.Base\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "Mapped \fBcollection\fP [str]"
.br
.ti -1c
.RI "Mapped \fBbook_id\fP = mapped_column(ForeignKey(Book\&.book_id))"
.br
.ti -1c
.RI "Mapped \fBcollection_id\fP = mapped_column(primary_key=True)"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
Collection model\&.
.fi
.PP

.SH "Member Data Documentation"
.PP
.SS "Mapped src\&.backend\&.lib\&.models\&.Collection\&.book_id = mapped_column(ForeignKey(Book\&.book_id))\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Collection\&.collection [str]\fC [static]\fP"

.SS "Mapped src\&.backend\&.lib\&.models\&.Collection\&.collection_id = mapped_column(primary_key=True)\fC [static]\fP"


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
