repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/fsouza/autoflake8
    rev: v0.4.0
    hooks:
    -   id: autoflake8
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
