#!python
import os


class RequiredPackages:
    def __init__(self, bins):
        self.required = bins
        self.to_be_installed = []
        self.locate()

    def locate(self):
        breakpoint()
        for bin in self.required:
            if os.path.isfile(bin[1]):
                continue
            else:
                self.to_be_installed.append(bin[0])
        return self.to_be_installed


# Package List
package_list = [["gcc", "/usr/bin/gcc"]]
packages, required_packages = "", RequiredPackages(package_list)
for package in required_packages:
    packages = packages + package[0] + " "
os.system("sudo pacman -S %s" % packages)
