.TH "app.lib.pyShelf.RequestHandler" 3 "Sun Nov 10 2019" "Version 0.1.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app.lib.pyShelf.RequestHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseHTTPRequestHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBdo_GET\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
Request Handler
.fi
.PP


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
