.TH "app.lib.pyShelf.BookServer" 3 "Sun Nov 10 2019" "Version 0.1.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app.lib.pyShelf.BookServer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBclose_prompt\fP (self)"
.br
.ti -1c
.RI "def \fBrun\fP (self)"
.br
.ti -1c
.RI "def \fBclose\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBserver_address\fP"
.br
.ti -1c
.RI "\fBhandler\fP"
.br
.ti -1c
.RI "\fBhttpd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
HTTP server functions required to display e-books

.fi
.PP

.SH "Member Function Documentation"
.PP
.SS "def app\&.lib\&.pyShelf\&.BookServer\&.close ( self)"

.PP
.nf
Stop HTTP Server
.fi
.PP

.SS "def app\&.lib\&.pyShelf\&.BookServer\&.close_prompt ( self)"

.PP
.nf
Prompt to close server
.fi
.PP

.SS "def app\&.lib\&.pyShelf\&.BookServer\&.run ( self)"

.PP
.nf
Start HTTP Server
.fi
.PP


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
