.TH "app.lib.display.Frontend" 3 "Sun Nov 10 2019" "Version 0.1.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app.lib.display.Frontend
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, dimensions=[0, 0])"
.br
.ti -1c
.RI "def \fBhtml_Headers\fP (self)"
.br
.ti -1c
.RI "def \fBapp_Headers\fP (self)"
.br
.ti -1c
.RI "def \fBapp_body\fP (self, nav, shelf)"
.br
.ti -1c
.RI "def \fBapp_footer\fP (self)"
.br
.ti -1c
.RI "def \fBcompile\fP (self, nav, shelf)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdimensions\fP"
.br
.ti -1c
.RI "\fBTITLE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
Dynamic frontend display functions
.fi
.PP

.SH "Constructor & Destructor Documentation"
.PP
.SS "def app\&.lib\&.display\&.Frontend\&.__init__ ( self,  dimensions = \fC[0, 0]\fP)"

.PP
.nf
:param dimensions: array containing screen size [x, y]

.fi
.PP

.SH "Member Function Documentation"
.PP
.SS "def app\&.lib\&.display\&.Frontend\&.app_body ( self,  nav,  shelf)"

.PP
.nf
Main interface body, and navigation
:param nav: nav[] system navigation list
:param shelf: shelf[0{path:"",title:"",cover:"",author:""}]
:returns _body: HTML render of page body

.fi
.PP

.SS "def app\&.lib\&.display\&.Frontend\&.app_footer ( self)"

.PP
.nf
Main interface footer; Closes HTML
:returns _footer: HTML render of page footer

.fi
.PP

.SS "def app\&.lib\&.display\&.Frontend\&.app_Headers ( self)"

.PP
.nf
App specific headers
:returns _head: HTML render of application specific headers

.fi
.PP

.SS "def app\&.lib\&.display\&.Frontend\&.compile ( self,  nav,  shelf)"

.PP
.nf
Compiles user interface
:returns _ui: Compiled HTML for page layout

.fi
.PP

.SS "def app\&.lib\&.display\&.Frontend\&.html_Headers ( self)"

.PP
.nf
HTML headers
:returns _head: HTML render of page headers

.fi
.PP


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
