.TH "app.config.Config" 3 "Sun Nov 10 2019" "Version 0.1.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app.config.Config
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbook_path\fP"
.br
.ti -1c
.RI "\fBTITLE\fP"
.br
.ti -1c
.RI "\fBbook_shelf\fP"
.br
.ti -1c
.RI "\fBcatalogue_db\fP"
.br
.ti -1c
.RI "\fBfile_array\fP"
.br
.ti -1c
.RI "\fBauto_scan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
Main System Configuration
.fi
.PP


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
