.TH "pyShelf.src.backend.lib.api_hooks.DuckDuckGo" 3 "Sun Dec 15 2019" "Version 0.3.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyShelf.src.backend.lib.api_hooks.DuckDuckGo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBimage_result\fP (self, query)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBurl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
duckduckgo related searching
.fi
.PP

.SH "Member Function Documentation"
.PP
.SS "def pyShelf\&.src\&.backend\&.lib\&.api_hooks\&.DuckDuckGo\&.image_result ( self,  query)"

.PP
.nf
Returns json containing url to image
:param _key: &t=h_&iar=images&iax=images&ia=images&format=json&pretty=1

.fi
.PP


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
