.TH "pyShelf.src.interface.models.Books.Meta" 3 "Sun Dec 1 2019" "Version 0.2.1" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyShelf.src.interface.models.Books.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBdb_table\fP = 'books'"
.br
.in -1c
.SH "Detailed Description"
.PP


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
