.TH "pyShelf.src.interface.apps.InterfaceConfig" 3 "Sun Dec 1 2019" "Version 0.2.1" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyShelf.src.interface.apps.InterfaceConfig
.SH SYNOPSIS
.br
.PP
.PP
Inherits AppConfig\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP = 'interface'"
.br
.in -1c
.SH "Detailed Description"
.PP


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
