.TH "pyShelf.src.frontend.urls" 3 "Sun Dec 1 2019" "Version 0.2.1" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyShelf.src.frontend.urls
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBurlpatterns\fP"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
frontend URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))

.fi
.PP

.SH "Variable Documentation"
.PP
.SS "list pyShelf\&.src\&.frontend\&.urls\&.urlpatterns"
\fBInitial value:\fP
.PP
.nf
1 =  [
2     path("admin/", admin\&.site\&.urls),
3     path("", views\&.index, name="index"),
4     path("download/<pk>", views\&.download, name="download"),
5     path("prev_page/<bookset>", views\&.prev_page, name="prev_page"),
6     path("next_page/<bookset>", views\&.next_page, name="next_page"),
7 ]
.fi
.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
