.TH "src.backend.lib.config.Config" 3 "Mon Aug 3 2020" "Version 0.6.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.lib.config.Config
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBsrc\&.backend\&.tests\&.library_test\&.Test_Config\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, root)"
.br
.ti -1c
.RI "def \fBopen_file\fP (self, _cp)"
.br
.ti -1c
.RI "def \fBdjango_secret\fP (self, _data)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbook_path\fP"
.br
.ti -1c
.RI "\fBTITLE\fP"
.br
.ti -1c
.RI "\fBVERSION\fP"
.br
.ti -1c
.RI "\fBbook_shelf\fP"
.br
.ti -1c
.RI "\fBcatalogue_db\fP"
.br
.ti -1c
.RI "\fBuser\fP"
.br
.ti -1c
.RI "\fBpassword\fP"
.br
.ti -1c
.RI "\fBdb_host\fP"
.br
.ti -1c
.RI "\fBdb_port\fP"
.br
.ti -1c
.RI "\fBfile_array\fP"
.br
.ti -1c
.RI "\fBroot\fP"
.br
.ti -1c
.RI "\fBauto_scan\fP"
.br
.ti -1c
.RI "\fBallowed_hosts\fP"
.br
.ti -1c
.RI "\fBdb_user\fP"
.br
.ti -1c
.RI "\fBdb_pass\fP"
.br
.ti -1c
.RI "\fBSECRET\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Main System Configuration

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.backend\&.lib\&.config\&.Config\&.__init__ ( self,  root)"

.PP
.nf
Initialize main configuration options

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def src\&.backend\&.lib\&.config\&.Config\&.open_file ( self,  _cp)"

.PP
.nf
Opens config.json and reads in configuration options

.fi
.PP
 
.PP
Reimplemented in \fBsrc\&.backend\&.tests\&.library_test\&.Test_Config\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
