.TH "src.backend.lib.display.TerminalDisplay" 3 "Wed Jan 1 2020" "Version 0.4.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.lib.display.TerminalDisplay
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBscreen\fP (self)"
.br
.ti -1c
.RI "def \fBinstaller\fP (self)"
.br
.ti -1c
.RI "def \fBprompt\fP (self, questions)"
.br
.ti -1c
.RI "def \fBh_rule\fP (self)"
.br
.ti -1c
.RI "def \fBbanner\fP (self)"
.br
.ti -1c
.RI "def \fBbanner_render\fP (self)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBclear\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBterm\fP"
.br
.ti -1c
.RI "\fBy\fP"
.br
.ti -1c
.RI "\fBhome\fP"
.br
.ti -1c
.RI "\fBuser\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBslogan\fP"
.br
.ti -1c
.RI "\fBgreen\fP"
.br
.ti -1c
.RI "\fBblue\fP"
.br
.ti -1c
.RI "\fBclr_term\fP"
.br
.in -1c
.SH "Detailed Description"
.PP


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
