.TH "src.backend.lib.pyShelf.InitFiles" 3 "Sun Feb 2 2020" "Version 0.4.1" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.lib.pyShelf.InitFiles
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, file_array)"
.br
.ti -1c
.RI "def \fBCreateFile\fP (self, _pointer)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
First run file creation operations
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def src\&.backend\&.lib\&.pyShelf\&.InitFiles\&.CreateFile ( self,  _pointer)"

.PP
.nf
Checks if file exists and creates it if not

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
