.TH "src.backend.tests.library_test.Test_Catalogue" 3 "Mon Aug 3 2020" "Version 0.6.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.tests.library_test.Test_Catalogue
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsrc\&.backend\&.lib\&.library\&.Catalogue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBfilter_books\fP (self)"
.br
.ti -1c
.RI "def \fBscan_folder\fP (self, _path=None)"
.br
.ti -1c
.RI "def \fBprocess_by_filetype\fP (self, book)"
.br
.ti -1c
.RI "def \fBextract_metadata_epub\fP (self, book)"
.br
.ti -1c
.RI "def \fBextract_metadata_mobi\fP (self, book)"
.br
.ti -1c
.RI "def \fBextract_content\fP (self, book_zip, book)"
.br
.ti -1c
.RI "def \fBextract_cover_html\fP (self, book_zip, book)"
.br
.ti -1c
.RI "def \fBextract_cover_image\fP (self, book_zip, book)"
.br
.ti -1c
.RI "def \fBcompare_shelf_current\fP (self)"
.br
.ti -1c
.RI "def \fBimport_books\fP (self, list=None)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBprocess_epub\fP (book)"
.br
.ti -1c
.RI "def \fBstripTags\fP (source)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbook_shelf\fP"
.br
.ti -1c
.RI "\fBfile_list\fP"
.br
.ti -1c
.RI "\fBopf_regx\fP"
.br
.ti -1c
.RI "\fBcover_regx\fP"
.br
.ti -1c
.RI "\fBhtml_regx\fP"
.br
.ti -1c
.RI "\fBtitle_sanitization_regx\fP"
.br
.ti -1c
.RI "\fBtitle_sanitization_lvl2_regx\fP"
.br
.ti -1c
.RI "\fBtitle_sanitization_dirs_regx\fP"
.br
.ti -1c
.RI "\fBroot_dir\fP"
.br
.ti -1c
.RI "\fBbook_folder\fP"
.br
.ti -1c
.RI "\fBbooks\fP"
.br
.ti -1c
.RI "\fBdb_pointer\fP"
.br
.ti -1c
.RI "\fBconfig\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Member Function Documentation"
.PP 
.SS "def src\&.backend\&.lib\&.library\&.Catalogue\&.compare_shelf_current ( self)\fC [inherited]\fP"

.PP
.nf
Calls storage system, gets list of books stored and compares against files on disk

.fi
.PP
 
.SS "def src\&.backend\&.lib\&.library\&.Catalogue\&.extract_content ( self,  book_zip,  book)\fC [inherited]\fP"

.PP
.nf
Opens epub as zip file filters then stores as list any files matching opf_regx

.fi
.PP
 
.SS "def src\&.backend\&.lib\&.library\&.Catalogue\&.extract_cover_html ( self,  book_zip,  book)\fC [inherited]\fP"

.PP
.nf
Opens epub as zip file filters then stores as list any files matching html_regx

.fi
.PP
 
.SS "def src\&.backend\&.lib\&.library\&.Catalogue\&.extract_cover_image ( self,  book_zip,  book)\fC [inherited]\fP"

.PP
.nf
Opens epub as zip file filters then stores as list any files matching cover_regx

.fi
.PP
 
.SS "def src\&.backend\&.lib\&.library\&.Catalogue\&.extract_metadata_epub ( self,  book)\fC [inherited]\fP"

.PP
.nf
Return extracted metadata and cover picture
book['path'] == Full path to ebook file
book['files'] == list of files from self.process_book(book)

.fi
.PP
 
.SS "def src\&.backend\&.tests\&.library_test\&.Test_Catalogue\&.filter_books ( self)"

.PP
.nf
Calls scan_folder and filters out book files
Proceeds to call process_book

:returns self._book_list_expanded: json string containing all book metadata

.fi
.PP
 
.PP
Reimplemented from \fBsrc\&.backend\&.lib\&.library\&.Catalogue\fP\&.
.SS "def src\&.backend\&.lib\&.library\&.Catalogue\&.import_books ( self,  list = \fCNone\fP)\fC [inherited]\fP"

.PP
.nf
Main entry point for import operations.
Gets a list of new files via compare_shelf_current.
Iterates over list and inserts new books into database.

.fi
.PP
 
.SS "def src\&.backend\&.lib\&.library\&.Catalogue\&.process_epub ( book)\fC [static]\fP, \fC [inherited]\fP"

.PP
.nf
Return dictionary of epub file contents
.fi
.PP
 
.SS "def src\&.backend\&.lib\&.library\&.Catalogue\&.scan_folder ( self,  _path = \fCNone\fP)\fC [inherited]\fP"

.PP
.nf
Scan folder by _path, allows recurisive scanning

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
