.TH "src.backend.lib.pyShelf.BookDisplay" 3 "Sun Feb 2 2020" "Version 0.4.1" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.lib.pyShelf.BookDisplay
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, **kwargs)"
.br
.ti -1c
.RI "def \fBnextPage\fP (self)"
.br
.ti -1c
.RI "def \fBpreviousPage\fP (self)"
.br
.ti -1c
.RI "def \fBbooksPerPage\fP (self, screen_size)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbooks_per_page\fP"
.br
.ti -1c
.RI "\fBcurrent_page\fP"
.br
.ti -1c
.RI "\fBthumbnail_size\fP"
.br
.ti -1c
.RI "\fBthumbnail_scale\fP"
.br
.ti -1c
.RI "\fBtotal_pages\fP"
.br
.ti -1c
.RI "\fBscreen_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP

.PP
.nf
All functions related to displaying book information in the HTML UI
.fi
.PP

.SH "Constructor & Destructor Documentation"
.PP
.SS "def src\&.backend\&.lib\&.pyShelf\&.BookDisplay\&.__init__ ( self, ** kwargs)"

.PP
.nf
Initialize class variables
:return: None

.fi
.PP

.SH "Member Function Documentation"
.PP
.SS "def src\&.backend\&.lib\&.pyShelf\&.BookDisplay\&.booksPerPage ( self,  screen_size)"

.PP
.nf
## TODO Remove me
Set books per page
:param screen_size: Array containing x,y pixel sizes
:return: self.books_per_page

.fi
.PP

.SS "def src\&.backend\&.lib\&.pyShelf\&.BookDisplay\&.nextPage ( self)"

.PP
.nf
## TODO Remove me
Goto next book page
:return: new current_page

.fi
.PP

.SS "def src\&.backend\&.lib\&.pyShelf\&.BookDisplay\&.previousPage ( self)"

.PP
.nf
## TODO Remove me
Goto previous book page
:return: new current_page

.fi
.PP


.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
