.TH "src.backend.tests.library_test.Test_Config" 3 "Wed Jan 1 2020" "Version 0.4.0" "pyShelf Open Source Ebook Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.backend.tests.library_test.Test_Config
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsrc\&.backend\&.lib\&.config\&.Config\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBopen_file\fP (self, root='config\&.json')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbook_path\fP"
.br
.ti -1c
.RI "\fBTITLE\fP"
.br
.ti -1c
.RI "\fBVERSION\fP"
.br
.ti -1c
.RI "\fBbook_shelf\fP"
.br
.ti -1c
.RI "\fBcatalogue_db\fP"
.br
.ti -1c
.RI "\fBuser\fP"
.br
.ti -1c
.RI "\fBpassword\fP"
.br
.ti -1c
.RI "\fBdb_host\fP"
.br
.ti -1c
.RI "\fBdb_port\fP"
.br
.ti -1c
.RI "\fBfile_array\fP"
.br
.ti -1c
.RI "\fBroot\fP"
.br
.ti -1c
.RI "\fBauto_scan\fP"
.br
.ti -1c
.RI "\fBallowed_hosts\fP"
.br
.ti -1c
.RI "\fBdb_user\fP"
.br
.ti -1c
.RI "\fBdb_pass\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
.SH "Member Function Documentation"
.PP
.SS "def src\&.backend\&.tests\&.library_test\&.Test_Config\&.open_file ( self,  _cp = \fC'config\&.json'\fP)"

.PP
.nf
Opens config.json and reads in configuration options

.fi
.PP

.PP
Reimplemented from \fBsrc\&.backend\&.lib\&.config\&.Config\fP\&.

.SH "Author"
.PP
Generated automatically by Doxygen for pyShelf Open Source Ebook Server from the source code\&.
